### PR TITLE
Fix #17

### LINKED ISSUE #17: browserstackLocal.stop hangs when running on jenkins/docker
I'm encountering a similar issue to the one reported [here](https://github.com/browserstack/browserstack-local-nodejs/issues/41). It seems that browserstackLocal.stop never calls the callback on my setup, thus leaving the test hanging on jenkins.

I think I could solve the issue by adding an option to this service to kill the process like suggested [here](https://github.com/browserstack/browserstack-local-nodejs/issues/36#issuecomment-330569897).

Would you accept a PR that implements this feature?

### PR DESCRIPTION
**Pull request by aberonni**
This PR tries to fix #17 by adding an option.

I'm not too sure that the option is aptly named, there might also be a better way of handling this but I've tested it for my use case and it fixes the issue.

### CODE REVIEW

**Comment by aberonni** [comment]
It seems that this PR is failing because a travis file is missing. I have added a travis file in #19 to fix this.

**Comment by itszero** [comment]
Can we do a quick rebase here to see if the new travis.yml works? 😄

**Comment by aberonni** [comment]
Yep just rebased that for you!

**Comment by itszero** [comment]
Thank you so much!

**Comment by itszero** [comment]
0.1.14 published

**Comment by aberonni** [comment]
Thank you!

Il sab 6 gen 2018, 07:15 Zero Cho <notifications@github.com> ha scritto:

**Pull request merged**
